# -*- coding: utf-8 -*-
"""Python Programming Basic Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPBkxYg7Uwz72nFyOXN8bsK0gJgFMHBs

**Python Programming Basic Assignment 4**

1. Write a Python Program to Find the Factorial of a Number?
"""

num = 5
factorial_num = 1
for i in range (1,num+1):
  factorial_num = factorial_num * i

print(factorial_num)

"""2. Write a Python Program to Display the multiplication Table?

"""

Table_of_num = int(input("number"))

Table_of_number = []

for i in range (1,11):
  a = Table_of_num * i

  Table_of_number.append(a)

print(Table_of_number)

"""3. Write a Python Program to Print the Fibonacci sequence?

"""

# number is the sum of perious two numbers

def fibonacci(n):
  a = 0
  b = 1

  if n < 0:
    print("incorrect input")
  elif n == 1:
    return b

  else:
    for i in range(1,n):
      c = a+b
      a = b
      b = c

    return b
  
print(fibonacci(4))

"""4. Write a Python Program to Check Armstrong Number?

"""

num = input("number")
l=len(num)
x=0
sum=0

c = int(num)

for i in range(0, l):
  x = int(num[i])
  sum = sum + x**l

if sum == c:
  print("armstrong")

else:
  print("not armstrong")

"""5. Write a Python Program to Find Armstrong Number in an Interval?

"""

# % --> get the remainder
# // --> get the quotient

for num in range(100,1000):
  temp=num
  sum=0
  while temp>0:
      digit=temp%10
      sum=sum+digit**3
      temp=temp//10
      if sum==num:
           print (num)

"""6. Write a Python Program to Find the Sum of Natural Numbers?"""

# sum of n natural numbers = n/2(2a+(n-1)d)  or n(n+1)/2

# sum of the natural numbers from 1 to 100

a = 1
n = 100
d = 1

sum = n/2 * (2*a + (n-1) * d)

print(sum)

# another way

num = int(input("Enter the value of n: "))

hold = num
sum = 0

if num<=0:
  print("enter positive input")

else:
  while num>0:
    sum = sum + num
    num = num - 1

  print("sum of", hold, "natural no is", sum)